apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tester-role
  namespace: default
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "pipelineruns", "tasks"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]